services:
  app:
    build:
      context: . # Path to the directory containing your Dockerfile
      dockerfile: dockerfile # Path to your Dockerfile (ensure the case is correct)
    container_name: dockerApp # Name of the container
    ports:
      - "8001:80" # Map port 80 in the container to port 8001 on the host
    volumes:
      - .:/app # Mount the current directory to /app in the container
    environment:
      - PHP_INI_DIR=/usr/local/etc/php # Optional: Define environment variables
    networks:
      - laravel # Connect the app service to the laravel network

  db: # Define a service for your database
    image: mysql:5.7 # Specify a version for compatibility
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laraveluser
      MYSQL_ROOT_PASSWORD: rootpassword # Root password is generally required
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql # Use a named volume for the database
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  db_data:
